### ISSUE TITLE
Feature: PHP 8.x support

### ISSUE THREAD

**Issue by josefglatz** [Apen/recordsmanager#11]
Would be nice if your extension supports the actual TYPO3 version also with PHP version 8.1

**Comment by Apen** [comment]
Yes, i'm on it :-)

**Comment by Apen** [comment]
i see that you start something here https://github.com/josefglatz/recordsmanager/tree/patch-1 , how far are you @josefglatz ?

**Comment by josefglatz** [comment]
### Yes, that branch you mentioned is the actual state.

As I don't know all areas of your extension it was not easy to make more fixes. I hope my commits helps a little bit. I wil create a PR in just a second!

### From my side I found following places where undefined array keys are present:

**Edit Backend Module:**
- PHP Warning: Undefined array key "uid" in /var/www/html/public/typo3conf/ext/recordsmanager/Classes/Utility/Config.php line 127


**Export Backend Module:**

PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key "uid" in /var/www/html/public/typo3conf/ext/recordsmanager/Classes/Utility/Config.php line 127

PHP Warning
Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in /var/www/html/public/typo3conf/ext/recordsmanager/Classes/Utility/Config.php line 127

PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key "uid" in /var/www/html/public/typo3conf/ext/recordsmanager/Classes/Utility/Config.php line 170

PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key "uid" in /var/www/html/public/typo3conf/ext/recordsmanager/Classes/Utility/Config.php line 179

PHP Warning
Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in /var/www/html/public/typo3conf/ext/recordsmanager/Classes/Utility/Config.php line 179

PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key "uid" in /var/www/html/public/typo3conf/ext/recordsmanager/Classes/Utility/Config.php line 220

PHP Warning
Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in /var/www/html/public/typo3conf/ext/recordsmanager/Classes/Utility/Config.php line 220

PHP Warning
Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in /var/www/html/public/typo3/sysext/backend/Classes/Form/Element/InputDateTimeElement.php line 84

PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key "processedTca" in /var/www/html/public/typo3/sysext/backend/Classes/Form/FieldWizard/OtherLanguageContent.php line 43

PHP Warning
Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in /var/www/html/public/typo3/sysext/backend/Classes/Form/FieldWizard/OtherLanguageContent.php line 43

PHP Warning
Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in /var/www/html/public/typo3/sysext/backend/Classes/Form/FieldWizard/OtherLanguageContent.php line 44

PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key "databaseRow" in /var/www/html/public/typo3/sysext/backend/Classes/Form/FieldWizard/DefaultLanguageDifferences.php line 43

PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key "tableName" in /var/www/html/public/typo3/sysext/backend/Classes/Form/FieldWizard/DefaultLanguageDifferences.php line 44

PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key "processedTca" in /var/www/html/public/typo3/sysext/backend/Classes/Form/FieldWizard/DefaultLanguageDifferences.php line 46

PHP Warning
Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in /var/www/html/public/typo3/sysext/backend/Classes/Form/FieldWizard/DefaultLanguageDifferences.php line 49

PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key "tableName" in /var/www/html/public/typo3/sysext/backend/Classes/Form/Element/InputDateTimeElement.php line 74

PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key "databaseRow" in /var/www/html/public/typo3/sysext/backend/Classes/Form/Element/InputDateTimeElement.php line 76

PHP Warning
Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in /var/www/html/public/typo3/sysext/backend/Classes/Form/Element/InputDateTimeElement.php line 84

PHP Warning
Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in /var/www/html/public/typo3/sysext/backend/Classes/Form/FieldWizard/OtherLanguageContent.php line 43

PHP Warning
Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in /var/www/html/public/typo3/sysext/backend/Classes/Form/FieldWizard/OtherLanguageContent.php line 44

**Comment by Apen** [comment]
Thanks a lot for this informations, i merged it and will fix all the remaining one.

**Comment by Apen** [comment]
Should be good in last commit
