### ISSUE TITLE
Update removed 'uploadfolder' TCA option

### ISSUE THREAD

**Issue by josefglatz** [Apen/recordsmanager#12]
`$GLOBALS['TCA'][$table]['columns'][$fieldName]['config']['uploadfolder']` "uploadfolder" is not available anymore.

**Comment by Apen** [comment]
Thats an old one, i need to check that.

**Comment by Apen** [comment]
Fixed in last commit, not needed anymore https://github.com/Apen/recordsmanager/commit/405d54dae3f5bab8263a837c4a10f601b51b31ed
