### ISSUE TITLE
Hardcoded /typo3conf/ext/ path in exportToEXCEL require_once

### ISSUE THREAD

**Issue by markijan** [Apen/recordsmanager#14]
ExportController > exportToEXCEL use hardcoded /typo3conf/ext/ path.
This causes trouble in case ext is located in another directory.
https://github.com/Apen/recordsmanager/blob/615dcafc24b2f042041922cebba9f237e2b814a7/Classes/Controller/ExportController.php#L255

Fix:
        //require_once Environment::getPublicPath() . '/typo3conf/ext/recordsmanager/Resources/Private/Php/PHP_XLSXWriter/xlsxwriter.class.php';
        require_once \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('recordsmanager') . 'Resources/Private/Php/PHP_XLSXWriter/xlsxwriter.class.php';

**Comment by Apen** [comment]
Fixed in last commit.
Thanks for your suggestion and sorry for the delay...
