### ISSUE TITLE
BE Module not available for editors users configuration in TYPO3 v12

### ISSUE THREAD

**Issue by markijan** [Apen/recordsmanager#15]
Recordsmanager BE modules are not listed in common TYPO3 Backendgroup > Access List > Modules [groupMods] configuration in TYPO3 12.4.8.
Therefore is not possible to give permissions to these modules for non-admin BE users/usergroups.

Adding 'access' => 'user', for parent module BE config fixed issue for me
https://github.com/Apen/recordsmanager/blob/615dcafc24b2f042041922cebba9f237e2b814a7/Configuration/Backend/Modules.php#L10

    $conf = [
        'txrecordsmanagerM1' => [
            'labels' => 'LLL:EXT:recordsmanager/Resources/Private/Language/locallang.xlf:recordsmanagertitle',
            'iconIdentifier' => 'recordsmanager-main',
            'access' => 'user',                    // <- added config option
            'navigationComponent' => '',
            'aliases' => ['txrecordsmanagerM1'],
        ],
    ];

**Comment by Apen** [comment]
Fixed in last commit. Sorry for the delay...
