### ISSUE TITLE
The timestamp filter in the export seems to be broken

### ISSUE THREAD

**Issue by anton-esin** [Apen/recordsmanager#17]
Typo3 version: 11.5.36

We've installed the extension and created the export configuration, we see the list of all entries from database (all of them have timestamps), but when we try to use a timestamp filter it looks like it is not working (nothing is filtered and the chosen data are vanishing after we press OK button). We also tried to put a value "tstamp" into "Filter field (default tstamp)[exportfilterfield]" it didn't change anything. Are we missing something that we should do in order to force the filter to work properly?

**Comment by Apen** [comment]
Fixed in last PR
