### ISSUE TITLE
count Warning on empty tables

### ISSUE THREAD

**Issue by spharion88** [Apen/recordsmanager#6]
Hi,

I get a PHP count warning when switching to a table without data. By default TYPO3 will create an Exception for this warning.

PHP Warning: count(): Parameter must be an array or an object that implements Countable in /web/typo3conf/ext/recordsmanager/Classes/Utility/Query.php line 222

It is easy to workaround this error by disabling PHP Warnings or removing E_WARNING from [SYS][exceptionalErrors], but it is also easy to fix it by giving the $rows in Sng\Recordsmanager\Utility\Query a default value of an empty array (protected $rows = [];).

kind regards,
Phillip

**Comment by Apen** [comment]
Will fix that in the next version with LTS 9 & 10 compatibility.

**Comment by Apen** [comment]
Can you try the last git commit? Cannot reproduce the bug but i initialize this array

**Comment by spharion88** [comment]
I tried it with the latest commit and it solved the problem for me.

**Comment by Apen** [comment]
Ok, cool, and sorry for the delay. The next release will be compatible with 9 & 10 LTS. Thanks for you feedback.
